name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd build
          ctest -V
